const ROUTES = { USER: '/user' };

const SUCCESS = {
  USER: {
    USER_SUCCESSFULLY_CREATED: 'USER_SUCCESSFULLY_CREATED',
  },
};

const ERROR = {
  APP: {
    UNAUTHORIZED: 'UNAUTHORIZED',
  },
  USER: {
    EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_ID_NOT_VALID: 'USER_ID_NOT_VALID',
  },
};

module.exports = { ROUTES, SUCCESS, ERROR };
